# Data Aggregating/Cleaning

### Load ETF Data (KARS, DRIV, IDRV, LIT) from April 2019 to April 2025

In [1]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

# Initialize API and TimeSeries object
api_key = "97OGHWS77V9ZH0G7"
ts = TimeSeries(key=api_key, output_format="pandas")

# List of ETF tickers
tickers = ['KARS', 'DRIV', 'IDRV', 'LIT'] 
etf_data = {}

# Fetch and process each ETF
for ticker in tickers:
    data, _ = ts.get_daily(symbol=ticker, outputsize='full')
    # Extract and sort closing prices
    closes = data['4. close'].sort_index()
    etf_data[ticker] = closes

etf_df = pd.DataFrame(etf_data)
etf_df.index = pd.to_datetime(etf_df.index) # Ensure index is datetime

# Sort by date
etf_df = etf_df.sort_index()
etf_df.head()

            KARS  DRIV  IDRV     LIT
date
2010-07-23   NaN   NaN   NaN  16.090
2010-07-26   NaN   NaN   NaN  16.456
2010-07-27   NaN   NaN   NaN  16.390
2010-07-28   NaN   NaN   NaN  16.330
2010-07-29   NaN   NaN   NaN  16.820

In [2]:
etf_df = etf_df.dropna()
etf_df

               KARS    DRIV    IDRV    LIT
date
2019-04-18  22.5000  14.400  25.870  29.06
2019-04-22  22.5000  14.340  25.857  28.85
2019-04-23  22.3700  14.300  25.935  28.59
2019-04-24  22.3700  14.280  25.790  28.03
2019-04-25  21.9600  14.008  25.435  27.72
...             ...     ...     ...    ...
2025-05-09  21.1800  21.520  30.330  37.67
2025-05-12  21.9700  22.470  31.370  39.01
2025-05-13  21.9538  22.700  31.450  39.19
2025-05-14  21.9100  22.740  31.640  39.24
2025-05-15  21.6800  22.590  31.445  38.73

[1528 rows x 4 columns]

### Load company stock close price data

In [3]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

# Initialize API and TimeSeries object
api_key = "97OGHWS77V9ZH0G7"
ts = TimeSeries(key=api_key, output_format="pandas")

# List of company tickers
stock_tickers = ['TSLA', 'RIVN', 'BYDDY', 'NIO Inc.', 'LCID', 'F', 'HYMTF']
stock_data = {}

# Fetch and process each company
for ticker in stock_tickers:
    data, _ = ts.get_daily(symbol=ticker, outputsize='full')
    # Extract and sort closing prices
    closes = data['4. close'].sort_index()
    stock_data[ticker] = closes

stock_df = pd.DataFrame(stock_data)
stock_df.index = pd.to_datetime(stock_df.index)
stock_df = stock_df.sort_index()

# Drop rows with any NaN values
stock_df_clean = stock_df.dropna()
stock_df_clean

ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY.

### Load Green Commodities Metals Data

In [ ]:
metals = pd.read_csv("data/Commodities IMF Data/commodities_IMF.csv")
metals = metals.drop(columns=["Unnamed: 428", "Country Name", "Country Code", "Unit Code", "Attribute"],
                     errors="ignore")
metals = metals.drop_duplicates().reset_index(drop=True)

# Reshape Data to Long Format
metals = metals.melt(id_vars=["Commodity Name", "Commodity Code", "Unit Name"], 
                      var_name="Date", value_name="Value")

# Convert Date Column to datetime format
metals["Date"] = pd.to_datetime(metals["Date"].str.replace("M", "-", regex=False), format="%Y-%m")

metals = metals.dropna(subset=["Value"])
metals["Value"] = pd.to_numeric(metals["Value"], errors="coerce")
metals = metals.reset_index(drop=True)
metals